### ISSUE TITLE
微服务间feign调用出现zuul超时问题[Internal Server Error]TIMEOUT或者[Internal Server Error]GENERAL

### ISSUE THREAD

**Issue by annkee** [annkee/exception#4]
说明：本地启动4个spring boot微服务，相互之间feign调用返回数据几乎1s之内完成，但是将4个服务部署到dockers容器再访问，相互之间feign调用返回数据时间等待较长，大约在3/4s之间，并且有进入hystrix
问题：zuul超时[Internal Server Error]TIMEOUT或者[Internal Server Error]GENERAL
解决：之前一直尝试通过设置hystrix的超时设置，但是发现作用不大，后来看到网上的文章看到在zuul服务配置ribbon的连接超时，问题瞬间得到解决，通过压测并发基本上很快就得到了正确的响应结果。zuul中的配置文件加上：
```
ribbon:
  ReadTimeout: 20000 # 处理时间
  ConnectTimeout: 20000 # 连接时间
  MaxAutoRetries: 0 #最大自动重试次数
  MaxAutoRetriesNextServer: 1 # 换实例重试次数
  MaxTotalHttpConnections: 2000 # 最大http连接数，越大越好，但到到达一个临界点之后，就不会提高响应速度了
  MaxConnectionsPerHost: 1000 # 每个host连接数
```
原文：https://zoeminghong.github.io/2017/12/21/springcloud%E7%BD%91%E5%85%B3%E8%B0%83%E4%BC%9820171221/)
