### ISSUE TITLE
微服务之间feign调用成功但是还是进入调用方的hystrix

### ISSUE THREAD

**Issue by annkee** [annkee/exception#5]
### 微服务之间feign调用成功但是还是进入调用方的hystrix
原因：两个服务之间的超时时间较短，需要设置较长时间来让调用方接收数据
解决：在yml文件配置中设置断路器超时时间
```
feign:
    hystrix:
        enabled: true

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 200000
```
